In [1]:
#1 In machine learning, the polynomial kernel is a kernel function commonly used with support vector machines (SVMs) and other kernelized models, that represents the similarity of vectors (training samples) in a feature space over polynomials of the original variables, allowing learning of non-linear models.

In [2]:
#2ividing Data into Train/Test Sets.
#Training the Model.
#Making Predictions.
#Evaluating the Model.
#Interpreting Results.

In [3]:
#3 Parameter ε controls the width of the ε-insensitive zone, used to fit the training data. The value of ε can affect the number of support vectors used to construct the regression function. The bigger ε, the fewer support vectors are selected. On the other hand, bigger ε-values results in more flat estimates.

In [4]:
#4A smaller value of C leads to a larger margin but may misclassify some points, while a larger value of C leads to a smaller margin but fewer misclassifications. The parameter gamma defines how far the influence of a single training example reaches, with low values meaning 'far' and high values meaning 'close'


In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


In [78]:
from sklearn.datasets import load_diabetes

In [79]:
data=load_diabetes()

In [80]:
df=pd.DataFrame(data.data,columns=data.feature_names)

In [81]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [82]:
df['s']=df['s1']+df['s2']+df['s3']+df['s4']+df['s5']+df['s6']

In [83]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6         s  
0 -0.002592  0.019907 -0.017646 -0.122776  
1 -0.039493 -0.068332 -0.092204 -0.153229  
2 -0.002592  0.002861 -0.025930 -0.137811  
3  0.034309  0.022688 -0.009362  0.048778  
4 -0.002592 -0.031988 -0.046641 -0.053548

In [84]:
X=df.iloc[:,:-1]
Y=data.target

In [85]:
from sklearn.model_selection import train_test_split

In [86]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=100,random_state=20)

In [87]:
from sklearn.svm import SVC

In [88]:
svc=SVC(kernel='linear')

In [89]:
svc.fit(X_train,Y_train)

SVC(kernel='linear')

In [90]:
Y_pred=svc.predict(X_test)

In [91]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [92]:
Y_pred

array([200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200.])

In [93]:
print(accuracy_score(Y_pred,Y_test))
print(confusion_matrix(Y_pred,Y_test))

0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [94]:
from sklearn.model_selection import GridSearchCV

In [96]:
parameter={'C':[0.1,1,10,100,1000],
          'gamma':[1,0.1,0.01,0.001],
          'kernel':['linear']}

In [97]:
grid=GridSearchCV(SVC(),param_grid=parameter,refit=True,cv=5,verbose=4)

In [98]:
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.014 total time=   0.1s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.014 total time=   0.1s


/opt/conda/lib/python3.10/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.015 total time=   0.1s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.015 total time=   0.1s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.015 total time=   0.1s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.014 total time=   0.1s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.014 total time=   0.1s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.015 total time=   0.1s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.015 total time=   0.1s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.015 total time=   0.1s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.014 total time=   0.1s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.014 total time=   0.1s
[CV 3/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.015 total time=   0.1s
[CV 4/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.015 total time=   0.1s
[CV 5/5] END ..C=0.1, gamma=

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001], 'kernel': ['linear']},
             verbose=4)

In [99]:
grid.best_params_

{'C': 100, 'gamma': 1, 'kernel': 'linear'}

In [ ]:
Y2_pred=grid.p